/* The printed form is the F-US399-QS-36 log, filled in by typing instead of by
   hand. These read every word the app actually draws onto it, so anything the
   app decides to add on its own shows up here. */
const { test, expect } = require('@playwright/test');
const H = require('./helpers.js');

const CHECK = {
  time: '1000', name: 'Kobe Mensah',
  rows: [
    { trailer:'LR7524', product:'FRIES', set:'-10', temp:'-9.1', fuel:'FULL',
      intact:'Y', door:'20', escalate:[] },
    { trailer:'R25106', product:'BUNS', set:'OFF', temp:'—', fuel:'—', intact:'—',
      door:'—', escalate:['UNIT OFF'], action:'Called DC, unit restarted', escTo:'DC' },
  ],
};

/* every string the form draws, in order, with the colour it was drawn in */
const drawn = (page, check) => page.evaluate((c) => new Promise(res => {
  const words = [];
  const proto = CanvasRenderingContext2D.prototype;
  const real = proto.fillText;
  proto.fillText = function (t, x, y) {
    words.push({ text: String(t), colour: this.fillStyle, x: Math.round(x), y: Math.round(y) });
    return real.apply(this, arguments);
  };
  const d = Object.assign({ date: ycTodayISO(), ts: new Date().toISOString() }, c);
  drawYardPaper(d, () => { proto.fillText = real; res(words); });
}), check);

const asOffice = (page) => H.gotoApp(page, { user:{email:'office@martinbrower.com'}, role:'office' });

test('the form is headed the way the printed one is', async ({ page }) => {
  await asOffice(page);
  const w = await drawn(page, CHECK);
  const all = w.map(x => x.text).join(' | ');
  expect(all).toContain('F-US399-QS-36 Trailer Inspection Log');
  expect(all).toContain('Air temperature critical limits');
  expect(all).toContain('DATE:');
  expect(all).toContain('Time: 1000');
  expect(all).toContain('NAME: Kobe Mensah');
});

test('the Martin Brower mark is on it, not just the title', async ({ page }) => {
  await asOffice(page);
  const drewLogo = await page.evaluate(() => new Promise(res => {
    let drew = false;
    const proto = CanvasRenderingContext2D.prototype;
    const real = proto.drawImage;
    proto.drawImage = function () { drew = true; return real.apply(this, arguments); };
    drawYardPaper({ date: ycTodayISO(), time:'1000', name:'K', ts:new Date().toISOString(),
      rows:[{ trailer:'A', product:'B', set:'-10', temp:'-9.1', fuel:'FULL',
              intact:'Y', door:'20', escalate:[] }] },
      () => { proto.drawImage = real; res(drew); });
  }));
  expect(drewLogo, 'the sheet is headed by the mark, as the paper is').toBe(true);
});

test('the columns are the eight on the paper, and the last one is ESCALATE', async ({ page }) => {
  await asOffice(page);
  const all = (await drawn(page, CHECK)).map(x => x.text);
  for (const h of ['TRAILER#', 'PRODUCT', 'TEMP', 'FUEL', 'DOOR #'])
    expect(all, h).toContain(h);
  expect(all.join(' ')).toContain('*ESCALATE*');
  expect(all.join(' '), 'the paper has no ACTION column').not.toContain('ACTION');
});

test('the escalate column reads N/A or Escalate, and nothing else', async ({ page }) => {
  await asOffice(page);
  const w = await drawn(page, CHECK);
  // the column's cells, not its heading
  const col = w.filter(x => x.x > 900 && x.y > 350 && x.text !== '*ESCALATE*');
  expect(col.map(x => x.text).sort()).toEqual(['Escalate', 'N/A']);
  const esc = col.find(x => x.text === 'Escalate');
  expect(esc.colour, 'and Escalate is red').toBe('#c0392b');
});

test('nothing the app wants to say is on the form', async ({ page }) => {
  await asOffice(page);
  const all = (await drawn(page, CHECK)).map(x => x.text).join(' | ');
  for (const junk of [
    'Generated by',            // which app made it
    'Checkpoint',
    'Escalate to the DC if',   // the rule, restated at the foot
    'escalation',              // a running count in the corner
    'trailers ·',
    'Action:',                 // the officer's note, which has no box on paper
    'Called DC',
    'Raised with',
    'in range',
    '✓', '✔',
  ]) expect(all, 'the form must not carry: ' + junk).not.toContain(junk);
});

test('what the officer typed is still on the record, just not on the paper', async ({ page }) => {
  await asOffice(page);
  await page.evaluate((c) => {
    DB.yardchecks = [Object.assign({ date: ycTodayISO(), ts: new Date().toISOString() }, c)];
    ycPersistAll();
  }, CHECK);
  expect(await page.evaluate(() => DB.yardchecks[0].rows[1].action))
    .toBe('Called DC, unit restarted');
  expect(await page.evaluate(() => DB.yardchecks[0].rows[1].escTo)).toBe('DC');
});

test('every reading typed into the app is on the form', async ({ page }) => {
  await asOffice(page);
  const all = (await drawn(page, CHECK)).map(x => x.text);
  for (const v of ['LR7524', 'FRIES', '-10', '-9.1', 'FULL', 'Y', '20',
                   'R25106', 'BUNS', 'OFF'])
    expect(all, v + ' is missing from the form').toContain(v);
});

test('a check with one trailer still draws a full sheet', async ({ page }) => {
  await asOffice(page);
  const w = await drawn(page, { time:'0800', name:'A', rows:[
    { trailer:'X1', product:'P', set:'34', temp:'36.0', fuel:'FULL', intact:'Y', door:'2', escalate:[] }]});
  expect(w.map(x => x.text).join(' | ')).toContain('F-US399-QS-36 Trailer Inspection Log');
  expect(w.filter(x => x.x > 900 && x.y > 350 && x.text !== '*ESCALATE*')
          .map(x => x.text)).toEqual(['N/A']);
});

/* ---- pressing Print prints the sheet, once ---- */
async function openFiled(page) {
  await asOffice(page);
  await page.evaluate((c) => {
    DB.yardchecks = [Object.assign({ date: ycTodayISO(), ts: new Date().toISOString() }, c)];
    ycPersistAll(); go('block', false, '1000');
  }, CHECK);
  await expect(page.locator('#bkview_body .ycpaper img')).toBeVisible();
}

test('print emits one page: the sheet, and nothing around it', async ({ page }) => {
  await openFiled(page);
  await page.emulateMedia({ media: 'print' });
  const m = await page.evaluate(() => {
    const gone = (sel) => { const el = document.querySelector(sel);
      return !el || getComputedStyle(el).display === 'none'; };
    const img = document.querySelector('#bkview .ycpaper img').getBoundingClientRect();
    return {
      chrome: ['header', 'main', '#bkview .dvbar', '#bkview .bkvmeta'].every(gone),
      sheetShown: img.height > 100,
      // US Letter at 96dpi is 816x1056; one page means the sheet fits its height
      fitsOnePage: img.height <= document.documentElement.clientHeight + 2,
    };
  });
  expect(m.chrome, 'only the sheet prints').toBe(true);
  expect(m.sheetShown).toBe(true);
  expect(m.fitsOnePage, 'four pages meant the sheet was never capped to one').toBe(true);
});

test('nothing but the sheet contributes any printed height', async ({ page }) => {
  await openFiled(page);
  await page.emulateMedia({ media: 'print' });
  const m = await page.evaluate(() => {
    const img = document.querySelector('#bkview .ycpaper img').getBoundingClientRect();
    return { page: document.body.scrollHeight, sheet: Math.round(img.height) };
  });
  expect(m.page, 'trailing furniture is what turned one page into four')
    .toBeLessThanOrEqual(m.sheet + 40);
});
